### ISSUE TITLE
PPC

### ISSUE THREAD

**Issue by benjyz** [CoinVault/Nako#3]
PPC didn't work out of the box, see this line

https://github.com/CoinVault/Nako/blob/master/docker/peercoin/Dockerfile#L5

Coin_URL should probably be this, but not sure if this is binary. will see if I can fix
`ENV COIN_URL https://github.com/ppcoin/ppcoin/archive/v0.5.4ppc.tar.gz`

**Comment by dangershony** [comment]
Ah ops you are right its probably a copy past bug
