### ISSUE TITLE
Vin and Vout in Mongo

### ISSUE THREAD

**Issue by jhondev** [CoinVault/Nako#7]
Hi!

Is there a reason to not store vin and vout in mongo and instead query them directly from RPC?
https://github.com/CoinVault/Nako/blob/de57b118128c2d16d17e0a7e308d512b9082269c/core/Storage/Mongo/MongoData.cs#L200

**Comment by dangershony** [comment]
If I remember correctly just to save data in mongo as the vin/vout was not directly needed for the main api endpoints.

**Comment by jhondev** [comment]
As I see, the endpoint "GET /api/query/transaction/{transactionId}" query  transaction and block info from mongo and vin/vout info from RPC, I was thinking that is better to query everything from mongo and I wanted to make that change in a fork, but first I wanted to make sure that vin/vout queries weren't doing from the RPC for some special reason.

Thanks for the info.

**Comment by dangershony** [comment]
No special reason that I can remember no, maybe just time constraint.
It will be great if you make this change.
